apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: gp-prod
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
