apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: gp-dev
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
